name: team_sphere_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: any
  carousel_slider: any
  connectivity_plus: any
  dartz: any
  device_info_plus: any
  dio: any
  equatable: any
  expandable: any
  expandable_page_view: any
  file_picker: any
  flutter:
    sdk: flutter
  flutter_bloc: any
  flutter_html: any
  flutter_launcher_icons: any
  flutter_secure_storage: any
  flutter_widget_from_html: any
  fresh_dio: any
  get_it: any
  image_picker: any
  injectable: any
  intl: any
  jwt_decoder: any
  oktoast: any
  path: any
  permission_handler: any
  provider: any
  rxdart: any
  scrollable_positioned_list: any
  shared_preferences: any
  shimmer: any
  simple_moment: any
  syncfusion_flutter_pdfviewer: any
  page_view_dot_indicator: any
  sprintf: any
  url_launcher: any
  package_info: any
  logger: any
  cupertino_icons: any
  supabase_flutter: any
  go_router: any
  flutter_fancy_tree_view: any
  loading_animation_widget: any

dev_dependencies:
  build_runner: any
  flutter_gen_runner:
  change_app_package_name: any
  flutter_lints: any
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  injectable_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/splash_logo_3x.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: false

flutter:

  uses-material-design: true

  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-VariableFont_wght.ttf
